//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCardServer
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Category
    {
        public Category()
        {
            this.FlashCards = new HashSet<FlashCard>();
            this.SharedUsers = new HashSet<AspNetUser>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Language { get; set; }
        [DataMember]
        public bool IsPublic { get; set; }
        [DataMember]
        public string UserID { get; set; }
    
        public virtual ICollection<FlashCard> FlashCards { get; set; }
        public virtual AspNetUser User { get; set; }
        public virtual ICollection<AspNetUser> SharedUsers { get; set; }
    }
}
